#!/usr/bin/env python
"""
Copyright 2014 Wordnik, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class DetailsResponse:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            'also': 'list[str]',
            'antonyms': 'list[str]',
            'definitions': 'list[Definition]',
            'entails': 'list[str]',
            'hasCategories': 'list[str]',
            'hasInstances': 'list[str]',
            'hasMembers': 'list[str]',
            'hasParts': 'list[str]',
            'hasSubstances': 'list[str]',
            'hasTypes': 'list[str]',
            'hasUsages': 'list[str]',
            'inCategory': 'list[str]',
            'inRegion': 'list[str]',
            'instance_of': 'list[str]',
            'memberOf': 'list[str]',
            'partOf': 'list[str]',
            'pertainsTo': 'list[str]',
            'regionOf': 'list[str]',
            'similarTo': 'list[str]',
            'substanceOf': 'list[str]',
            'synonyms': 'list[str]',
            'typeOf': 'list[str]',
            'usageOf': 'list[str]'

        }


        #Phrases to which the original word belongs.
        self.also = None # list[str]
        #Words that have the opposite context of the original word.
        self.antonyms = None # list[str]
        #The meaning of the word, including it's part of speech.
        self.definitions = None # list[Definition]
        #Words that are implied by the original word. Usually used for verbs.
        self.entails = None # list[str]
        #Categories of the original word.
        self.hasCategories = None # list[str]
        #Words that are examples of the original word.
        self.hasInstances = None # list[str]
        #Words that belong to the group defined by the original word.
        self.hasMembers = None # list[str]
        #Words that are part of the original word. Also known as meronyms.
        self.hasParts = None # list[str]
        #Substances that are part of the original word.
        self.hasSubstances = None # list[str]
        #Words that are more specific than the original word. Also known as hyponyms.
        self.hasTypes = None # list[str]
        #Words that are examples of the domain the original word defines.
        self.hasUsages = None # list[str]
        #The domain category to which the original word belongs.
        self.inCategory = None # list[str]
        #Regions where the word is used.
        self.inRegion = None # list[str]
        #Words that the original word is an example of.
        self.instance_of = None # list[str]
        #A group to which the original word belongs.
        self.memberOf = None # list[str]
        #Partof
        self.partOf = None # list[str]
        #Words to which the original word is relevant
        self.pertainsTo = None # list[str]
        #A region where words are used.
        self.regionOf = None # list[str]
        #Words that similar to the original word, but are not synonyms.
        self.similarTo = None # list[str]
        #Substances to which the original word is a part of.
        self.substanceOf = None # list[str]
        #Words that can be interchanged for the original word in the same context.
        self.synonyms = None # list[str]
        #Words that are more generic than the original word. Also known as hypernyms.
        self.typeOf = None # list[str]
        #Words that the original word is a domain usage of.
        self.usageOf = None # list[str]
        
