#!/usr/bin/env python
#coding: utf8 
"""
WordAPI.py
Copyright 2014 Wordnik, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
"""
import sys
import os

from models import *


class WordsApi(object):

    def __init__(self, apiClient):
      self.apiClient = apiClient

    

    def details(self, accessToken, word, detail, **kwargs):
        """To retrieve a specific set of details of a word.

        Args:
            accessToken, str: API key or token for authorization (required)

            word, str: Word (required)

            detail, str: Detail (required)

            

        Returns: DetailsResponse
        """

        allParams = ['accessToken', 'word', 'detail']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method details" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/words/{word}/{detail}'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'GET'

        queryParams = {}
        headerParams = {}
        formParams = {}
        bodyParam = None

        if ('accessToken' in params):
            queryParams['accessToken'] = self.apiClient.toPathValue(params['accessToken'])
        if ('word' in params):
            replacement = str(self.apiClient.toPathValue(params['word']))
            resourcePath = resourcePath.replace('{' + 'word' + '}',
                                                replacement)
        if ('detail' in params):
            replacement = str(self.apiClient.toPathValue(params['detail']))
            resourcePath = resourcePath.replace('{' + 'detail' + '}',
                                                replacement)
        if formParams:
            headerParams['Content-type'] = 'application/x-www-form-urlencoded'

        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'DetailsResponse')
        return responseObject
        

        

    def get(self, accessToken, word, **kwargs):
        """ 

        Args:
            accessToken, str: API key or token for authorization (required)

            word, str: Word (required)

            

        Returns: WordResponse
        """

        allParams = ['accessToken', 'word']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method get" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/words/{word}'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'GET'

        queryParams = {}
        headerParams = {}
        formParams = {}
        bodyParam = None

        if ('accessToken' in params):
            queryParams['accessToken'] = self.apiClient.toPathValue(params['accessToken'])
        if ('word' in params):
            replacement = str(self.apiClient.toPathValue(params['word']))
            resourcePath = resourcePath.replace('{' + 'word' + '}',
                                                replacement)
        if formParams:
            headerParams['Content-type'] = 'application/x-www-form-urlencoded'

        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'WordResponse')
        return responseObject
        

        

    




